#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Generates a PifHuffmanCode table for pif_huffman from sample data.

Counts how often each byte value occurs in the sample files, builds a Huffman
code from those counts and prints it as C source for pifHuffman_InitEncoder()
and pifHuffman_Decode().

  - Every byte value gets a code, even one that never occurs in the samples,
    so any input can be encoded. Unseen values get the longest codes.
  - No code is longer than PIF_HUFFMAN_MAX_LENGTH (16) bits. If the plain
    Huffman code is deeper, the counts are flattened until it fits.
  - The codes are canonical: sorted by length, then by byte value. The same
    samples always give the same table.

The samples should look like the data the firmware will compress, for example
a few logs or packets captured from the real device.

Usage:
  tools/gen_huffman_table.py [-n NAME] [-o OUTPUT] SAMPLE [SAMPLE ...]

Example:
  tools/gen_huffman_table.py -n g_log_huffman -o log_huffman.c log1.bin log2.bin
"""

import argparse
import heapq
import sys

SYMBOLS = 256       # PIF_HUFFMAN_SYMBOLS
MAX_LENGTH = 16     # PIF_HUFFMAN_MAX_LENGTH


def count_bytes(paths):
    """Returns the occurrence count of each byte value over all files."""
    counts = [0] * SYMBOLS
    for path in paths:
        with open(path, "rb") as f:
            for byte in f.read():
                counts[byte] += 1
    return counts


def huffman_lengths(weights):
    """Returns the Huffman code length of each symbol for positive weights."""
    # Heap entries are (weight, order, symbols in the subtree). order breaks
    # ties so the result does not depend on how heapq compares lists.
    heap = [(w, i, [i]) for i, w in enumerate(weights)]
    heapq.heapify(heap)
    lengths = [0] * len(weights)
    order = len(weights)
    while len(heap) > 1:
        w1, _, s1 = heapq.heappop(heap)
        w2, _, s2 = heapq.heappop(heap)
        for s in s1 + s2:
            lengths[s] += 1
        heapq.heappush(heap, (w1 + w2, order, s1 + s2))
        order += 1
    return lengths


def limited_lengths(counts):
    """Returns code lengths of at most MAX_LENGTH bits.

    Unseen symbols count as 1. While the code is too deep, the counts are
    halved (staying at 1 or more), which pulls the rare symbols up.
    """
    weights = [c + 1 for c in counts]
    while True:
        lengths = huffman_lengths(weights)
        if max(lengths) <= MAX_LENGTH:
            return lengths
        weights = [max(1, w >> 1) for w in weights]


def canonical_codes(lengths):
    """Assigns canonical codes: shorter codes first, equal lengths by symbol."""
    codes = [0] * len(lengths)
    code = 0
    prev_length = 0
    for symbol in sorted(range(len(lengths)), key=lambda s: (lengths[s], s)):
        code <<= lengths[symbol] - prev_length
        codes[symbol] = code
        code += 1
        prev_length = lengths[symbol]
    return codes


def render(name, counts, lengths, codes, sources):
    """Returns the table as C source."""
    total = sum(counts)
    bits = sum(c * l for c, l in zip(counts, lengths))
    lines = [
        "// Generated by tools/gen_huffman_table.py from:",
    ]
    lines += ["//   %s" % s for s in sources]
    if total:
        lines.append("// Samples: %d bytes, %.3f bits per byte on average (%.1f %% of the original size)."
                     % (total, bits / total, 100.0 * bits / (total * 8)))
    lines += [
        "",
        '#include "codec/pif_huffman.h"',
        "",
        "const PifHuffmanCode %s[PIF_HUFFMAN_SYMBOLS] = {" % name,
        "//    code    length       byte  count",
    ]
    for symbol in range(SYMBOLS):
        lines.append("    { 0x%04X, %2d },    // 0x%02X  %d  %s"
                     % (codes[symbol], lengths[symbol], symbol, counts[symbol],
                        format(codes[symbol], "0%db" % lengths[symbol])))
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate a PifHuffmanCode table from sample data.")
    parser.add_argument("samples", nargs="+", help="sample files that look like the data to compress")
    parser.add_argument("-n", "--name", default="g_huffman_table", help="C name of the table (default: %(default)s)")
    parser.add_argument("-o", "--output", help="output .c file (default: standard output)")
    args = parser.parse_args()

    counts = count_bytes(args.samples)
    if not sum(counts):
        print("warning: the samples are empty; every byte gets an 8-bit code", file=sys.stderr)
    lengths = limited_lengths(counts)
    codes = canonical_codes(lengths)
    text = render(args.name, counts, lengths, codes, args.samples)

    if args.output:
        with open(args.output, "w", newline="\n") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
